server:
  port: 6666

spring:
  activemq:
    broker-url: tcp://192.168.43.223:61616  #自己的MQ服务器地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: true   #false:Queue     true:Topic   ,不写默认false
#定义自己的队列名称
mytopic: boot-activemq-topic